### ISSUE TITLE
Loose ends from repository move

### ISSUE THREAD

**Issue by ipelupessy** [omuse-geoscience/omuse#1]
please report all issues that arise from the move of the repository here.

just make a new issue if you want to reopen one of the issues from the old bitbucket repository.

**Comment by ipelupessy** [comment]
#2 Singularity recipe needs fix

**Comment by fjansson** [comment]
* Instruction still points to bitbucket: https://omuse.readthedocs.io/en/latest/installing.html

* The readthedocs build system seems to point to bitbucket

**Comment by ipelupessy** [comment]
fixed

**Comment by fjansson** [comment]
omuse/examples/README.md still points to bitbucket

it could also mention the application example directories
e.g. src/omuse/community/dales/example

**Comment by ipelupessy** [comment]
fixed. Maybe you can also push a Dales example to the omuse-examples repo?

**Comment by ipelupessy** [comment]
closing this, remaining problems should open a new issue
