### ISSUE TITLE
Loading DALES case fails

### ISSUE THREAD

**Issue by goord** [omuse-geoscience/omuse#10]
Loading the namelist of a predefined DALES case seems to be broken, we always end up with the default ones; this can simply be tested by calling
```
d = Dales(case="bomex", workdir="bomex-perf", number_of_workers=1)
print(d.parameters_DOMAIN.xlat)
```
which should print 15 instead of 54 in the bomex case.
The problem seems to originate from the call in the dales constructor
```
self.read_namelist_parameters(namelist)
```
which correctly assigns the ``self._parameters`` dictionary but not parameter groups like ``self.parameters_DOMAIN``

**Comment by ipelupessy** [comment]
fixed, but please check carefully because I am not sure the order of things in the __init__ is ok..

**Comment by ipelupessy** [comment]
prob fixed ok
