### ISSUE TITLE
i-emic interface dash problem

### ISSUE THREAD

**Issue by mchertova** [omuse-geoscience/omuse#20]
when prescribing forcing or other parameters via i-emic interface it is impossible to use dashes in straightforward way:
instead of instance.ocean__THCM.Global_Grid-Size_l
one has to do:
setattr(instance.ocean__THCM, "Global_Grid-Size_l", 32)
That's confusing.

**Comment by ipelupessy** [comment]
should be fixed now..

**Comment by ipelupessy** [comment]
ie, "-" is replaced by "_"

**Comment by merijn** [comment]
This issue can be closed now, right?

**Comment by ipelupessy** [comment]
jep
