### ISSUE TITLE
Can't set parameters in I-EMIC from OMUSE

### ISSUE THREAD

**Issue by Sbte** [omuse-geoscience/omuse#22]
As the title says. I can set parameters at the start, I think, but not at any point after some computation has happened (I assume this is after `commit_parameters` is called, who knows when that is). This makes sense since `setParameters` is not called anywhere but in `load_from_file`. If I try to add it in a reasonable place, I either get the error that I can't set parameters that are not in "Starting Parameters", which makes sense, since we don't allow online modification of those parameters from the I-EMIC side (but those are present in the ParamSet), but if I try to make a new `Techos::ParameterList` and only put the modified parameter in there (this is the proposed way of doing things from the I-EMIC side) I get an error because the `ParamSet` uses `getEntry` to set a parameter (and obviously the new parameter is not present in an empty list).

**Comment by merijn** [comment]
Should be addressed by https://github.com/merijn/omuse/tree/setparam but still needs tests.

**Comment by merijn** [comment]
Solved in the current `smcm` branch, so rebasing #24 to that should work.
