### ISSUE TITLE
Single string parameter accessors don't handle error returns in the high level interface

### ISSUE THREAD

**Issue by merijn** [omuse-geoscience/omuse#26]
The new accessors for `get_parameter_type`, `get_double_parameter`, `set_double_parameter`, etc. don't use the `remote_function` decorator and so aren't wrapped by the high-level interface to check the return code, returning an `OrderedDictionary` like the low level interface instead.

**Comment by merijn** [comment]
@ipelupessy
I was looking through the AMUSE wrapper code, but there doesn't seem to be a decorator that covers this case, I think it's probably better to add one to AMUSE than to manually override each function in the high-level interface with calls to the low level interface.

**Comment by ipelupessy** [comment]
yea you might be right..

**Comment by ipelupessy** [comment]
the alternative is to implement the get_double_parameter etc in the high level interface (the rationale is that low level should never be used directly anyway..)

**Comment by ipelupessy** [comment]
its enough to move them to the high level class...
