### ISSUE TITLE
Dales git repo looks funny..

### ISSUE THREAD

**Issue by ipelupessy** [omuse-geoscience/omuse#3]
namely: https://github.com/https://github.com/dalesteam/dales.git
in src/omuse/community/dales/Makefile

**Comment by ipelupessy** [comment]
also: what is the status of the official-dales branch??

**Comment by fjansson** [comment]
that's odd. I'll fix and test.

The official-dales branch is obsolete now. It was where I initially tested using omuse with the official dales.
