### ISSUE TITLE
Dales notebook example fails on second run

### ISSUE THREAD

**Issue by fjansson** [omuse-geoscience/omuse#4]
This issue is copied from the OMUSE bitbucket repo [issue 21](https://bitbucket.org/omuse/omuse/issues/21/dales-notebook-example-fails-on-second-run) .

The example notebook src/omuse/community/dales/example/bubble-notebook.ipynb works once but fails on the second run, presumably because the output directory and name list file from the previous run exist. 
```
d = Dales(workdir='bubble-nb', channel_type='sockets', number_of_workers=1)

Exception                                 Traceback (most recent call last)
<ipython-input-2-3a67f42204ee> in <module>
----> 1 d = Dales(workdir='bubble-nb', channel_type='sockets', number_of_workers=1)

/opt/omuse/src/omuse/community/dales/interface.py in __init__(self, **options)
    640         self.parameters.input_file = namelist
    641         if namelist is not None and os.path.isfile(namelist):
--> 642             self.read_namelist_parameters(namelist)
    643             self._nml_file = namelist
    644         else:

/usr/local/lib/python3.6/site-packages/amuse/support/parameter_tools.py in read_namelist_parameters(self, inputfile, add_missing_parameters)
    196
    197     def read_namelist_parameters(self, inputfile, add_missing_parameters=False):
--> 198         return self.read_parameters(inputfile,add_missing_parameters)
    199
    200     def output_format_value(self,value):

/usr/local/lib/python3.6/site-packages/amuse/support/parameter_tools.py in read_parameters(self, inputfile, add_missing_parameters)
    106                     name=self._parameters[key]["name"]
    107                     dtype=self._parameters[key]["dtype"]
--> 108                     val=self.interpret_value( rawval, dtype=dtype)
    109                     if is_quantity(self._parameters[key]["default"]):
    110                         self._parameters[key]["value"]=new_quantity(val, to_quantity(self._parameters[key]["default"]).unit)

    /usr/local/lib/python3.6/site-packages/amuse/support/parameter_tools.py in interpret_value(self, value, dtype)
     92
     93     def interpret_value(self,value, dtype=None):
---> 94         raise Exception("not implemented")
     95
     96     def read_parameters(self, inputfile, add_missing_parameters=False):

Exception: not implemented
```

This used to work - and still does in my singularity images from 2019-09-19.

**Comment by ipelupessy** [comment]
I have updated amuse parameter_tools to fix this (missing interpret_value)..can you try?

**Comment by ipelupessy** [comment]
maybe also check carefully the results and parameter file are ok (I changed quite a bit in the parameter handling of namelist files)

**Comment by ipelupessy** [comment]
(note to self: write more tests)

**Comment by fjansson** [comment]
This is still not in the pypi archive, right? I have amuse-framework 13.1.0 from pip, and there it still doesn't work. I looked at the AMUSE docs for how to do a development install of AMUSE, but didn't find it. Can I do development installs of both AMUSE and OMUSE?

**Comment by ipelupessy** [comment]
I don't think it is...yes you can do development install, however since OMUSE want amuse-framework you need to install it from the corresponding packages directory:
```
cd amuse
cd packages
cd amuse-framework
pip install -e .
```

**Comment by ipelupessy** [comment]
there should also be an update shortly..

**Comment by fjansson** [comment]
I did development installs of amuse-framework and omuse, this solved the problem. (It also solved the same problem when tarting from an existing case, e.g. case='rico'). 

A pip-installable amuse-framework release soonish would be nice to make this portable.

**Comment by ipelupessy** [comment]
the pypi package should have been updated now..

**Comment by ipelupessy** [comment]
this is fixed i think
