### ISSUE TITLE
DALES model cleanup_code() fails

### ISSUE THREAD

**Issue by fjansson** [omuse-geoscience/omuse#5]
Exception when calling cleanup_code() on a Dales object:
```
CodeException: Exception when calling function 'cleanup_code', of code 'DalesInterface', exception was 'lost connection to code'
```

Output from the dales model, in the terminal, when launched with `redirection='none'` to see the output:
```
 TOTAL wall time =    773.72791208199999     
*** The MPI_Comm_f2c() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```

So far I have tried this from a Jupyter notebook, with a single dales worker and using the sockets channel.

**Comment by ipelupessy** [comment]
this seems to be a double mpi_finalize...have you checked the cleanup code?

**Comment by fjansson** [comment]
You're right. It seems a change in exitmpi() in modmpi.f90 was lost when merging our dales fork into the official version. I'll fix it.

**Comment by fjansson** [comment]
Fixed in https://github.com/dalesteam/dales/commit/185f8a1ba1bfc345c882682ce60e6a75408e4d9b
